### model
model_name_or_path: ../qwen2-5-3b-base
trust_remote_code: true

### method
stage: pt
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z2_config.json

### dataset
dataset: tibetan_cpt_final
template: qwen
cutoff_len: 8192
overwrite_cache: true
preprocessing_num_workers: 128
dataloader_num_workers: 4

### output
output_dir: ../saves/qwen2.5-3b/full/cpt
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: false
save_only_model: false
save_total_limit: 10
report_to: tensorboard

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 4
learning_rate: 5.0e-5
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.03
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval
val_size: 0.01
per_device_eval_batch_size: 4
eval_strategy: steps
eval_steps: 100

